# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-09 06:33
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='url_map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100000)),
                ('short_url', models.CharField(max_length=1000)),
                ('created_by', models.CharField(max_length=100)),
                ('allowed_users', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=[], null=True, size=None)),
                ('visits', models.IntegerField(default=0)),
                ('expiry', models.IntegerField(default=10)),
                ('date_time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
